### ISSUE TITLE
Z Motors

### ISSUE THREAD

**Issue by spotless20** [PrintersForAnts/Tiny-T#1]
Hey, at first my full respect and thx to upsetting this guide :)

You write 3x 150mm V0.1 Motors, this are 200mm you linked and build in the v0.1.

Im just dump and misunderstood smth or is this okay so?

And 2nd. I can use the printer with the normal Steahlth/Afterburner and the Mini?

Thx and best Wishes.

**Comment by thiagolocatelli** [comment]
yeah, the v0.1 z stepper motors with leadscrew work and thats the one you should get. I may have made a mistake with the 150mm. Yes, you can use Stealthburner/Afterburner with it. I have been using SB.
