### ISSUE TITLE
Example configuration missing

### ISSUE THREAD

**Issue by Laroto** [PrintersForAnts/Tiny-T#15]
There is no configuration example in the files.

The gap between a new Voron builder and a TinyT builder is quite large due to the unofficial dimensions. 
Could someone add a example file?

**Comment by thiagolocatelli** [comment]
@Laroto Pedro, aqui tem um exemplo de config: https://github.com/DoubleT-PrinterConfigs/TinyTConfig

**Comment by thiagolocatelli** [comment]
also config added to readme.md file through pull request
