### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by W141-ID** [PrintersForAnts/Tiny-T#2]
Hey,

I am onto building a tiny-t and wanted to ask if there any updates coming or if this project is on ice.
A discord channel of some sort would also be awesome to link the tiny-t community.

**Comment by demizer** [comment]
Looks like v1.0 release was made today and it looks fantastic. Nice work folks!

**Comment by thiagolocatelli** [comment]
@demizer yeah, I have been working on the weekends on the Tiny-T revision 2 (with some new changes), that's why I created the "release" so there is something to always go back to in case needed.

**Comment by W141-ID** [comment]
> ...on the Tiny-T revision 2 (with some new changes)...

@thiagolocatelli So I guess revision 2 is on its way and this was just a little preview?

**Comment by thiagolocatelli** [comment]
@waym99 The revision 2 will have new changes, what you consider "a little preview" is part of revision 1, basically just new top hat. Revision 2 will have a few more changes. I created a separate branch where I will be publishing the r2 changes once I complete them.

**Comment by W141-ID** [comment]
@thiagolocatelli excited, keep us up to date please . I am building one right now. But will delay the build till rev2 is out.
