### ISSUE TITLE
Front idlers not in step file

### ISSUE THREAD

**Issue by flow23** [PrintersForAnts/Tiny-T#9]
Hi,
the front idlers from the github image is not in the step file.

![image](https://user-images.githubusercontent.com/3601005/221855967-9bf0d780-d566-4fdc-93a6-10baa3e571a4.png)

**Comment by thiagolocatelli** [comment]
@flow23 I shared the step file for those idlers in one of the TinyT build logs in the Doom Discord server. check it out.

**Comment by thiagolocatelli** [comment]
[front idlers v5.step.zip](https://github.com/PrintersForAnts/Tiny-T/files/10855531/front.idlers.v5.step.zip)
 @flow23 here they are in case you cant find.

**Comment by flow23** [comment]
Hi Thiago, is there a reason why you don't include it?

**Comment by thiagolocatelli** [comment]
@flow23 designed after
